version: "3"

networks:
  backend:
    driver: bridge

services:
  db:
    build: .docker/postgres
    container_name: sgp-db
    restart: always
    tty: true
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server
    volumes:
      - .docker/dbdata/redis:/data
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend
